### ISSUE TITLE
Unhandled exception in WebSocket 

### ISSUE THREAD

**Issue by ilsnk** [chronoxor/NetCoreServer#279]
**At random time we have this:**

Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at System.Runtime.CompilerServices.RuntimeHelpers.GetSubArray[T](T[] array, Range range)
   at NetCoreServer.WebSocket.PrepareReceiveFrame(Byte[] buffer, Int64 offset, Int64 size) in /src/websocket-server/NetCoreServer/WebSocket.cs:line 323
   at NetCoreServer.TcpSession.ProcessReceive(SocketAsyncEventArgs e) in /src/websocket-server/NetCoreServer/TcpSession.cs:line 624
   at NetCoreServer.TcpSession.OnAsyncCompleted(Object sender, SocketAsyncEventArgs e) in /src/websocket-server/NetCoreServer/TcpSession.cs:line 567
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by ilsnk** [comment]
We use latest library version

**Comment by selmanahatli** [comment]
I have same problem with 7.0.0 version. Is there any progress about this issue? 
Or could yo fix that in a different way? @ilsnk

**Comment by suleymanbyzt** [comment]
Same problem any update ?

**Comment by ilsnk** [comment]
We have not yet had time to independently study this problem. We are still getting this error.

**Comment by suleymanbyzt** [comment]
I still keep getting this error. How can I handle this? @chronoxor

`Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at NetCoreServer.WebSocket.PrepareReceiveFrame(Byte[] buffer, Int64 offset, Int64 size)
   at NetCoreServer.TcpSession.ProcessReceive(SocketAsyncEventArgs e)
   at NetCoreServer.TcpSession.OnAsyncCompleted(Object sender, SocketAsyncEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)`

thank you for your help in advance

**Comment by MrVitaly** [comment]
@ilsnk , @selmanahatli, @suleymanbyzt, do you have a stable way to reproduce it?

**Comment by chronoxor** [comment]
It'll great if we can reproduce it and try to fix. I cannot reproduce this on my side. And we have WebSockets server on production running for months without issues.

**Comment by ilsnk** [comment]
Maybe we are not using the server implementation correctly?
We have NetCoreServer acting as a socket, sending/receiving messages through our own abstract handlers.

**Comment by ilsnk** [comment]
We can assume that the problem may be in this code.
Processing goes _ProcessReceive_ is executed by asynchronous callback, lock is executed in _OnRecieve_. But since the callback (ProcessReceive) is executed from asynchronous callback code, by executing _Resize_ we ignore the lock object

TspSession.cs:602, 
WebSocket.cs:322

What do you think?

![image_2024-03-24_03-08-27](https://github.com/chronoxor/NetCoreServer/assets/44324620/05815eb5-9dfe-4105-aba4-3f5b60de1481)

**Comment by chronoxor** [comment]
Still not reproduced on my side.

For each session receive buffer resize `_receiveBuffer.Reserve(size + 1);` should be called after `OnReceived(_receiveBuffer.Data, 0, size) -> WebSocket.PrepareReceiveFrame(buffer, offset, size) -> lock (WsReceiveLock) { ... }` is executed, so the buffer should be still valid in PrepareReceiveFrame.

**Comment by daigs** [comment]
今天我也出现这个bug了,导致我的服务程序直接结束进程了.
我是刚开机时(服务程序加入了开机自动启动),马上打开浏览器通过网页请求我的服务出现问题的,
当时在网页上点击按钮请求服务时卡主了一会儿,然后我就使劲点了几下按钮继续请求,然后就弹出异常窗口后服务程序挂掉了...
然后我就重启我的服务程序,但是无论如何也出现不了这种异常了...
我重写了OnReceived如何用try...catch捕获异常,防止我的服务程序挂掉
![image](https://github.com/chronoxor/NetCoreServer/assets/25603166/2d0b391a-c1a6-439f-837b-881849455c7d)
![image](https://github.com/chronoxor/NetCoreServer/assets/25603166/b9eed67a-597a-4e06-8e10-13d627e6d095)

**Comment by ilsnk** [comment]
Perhaps due to an incorrect shift of payload bytes? I'm not sure what exactly the crash error is coming from, but is it worth rechecking this code?

https://github.com/chronoxor/NetCoreServer/blob/51d182341f3234367a5ef440ffb72d393a8a5f81/source/NetCoreServer/WebSocket.cs#L412

<img width="1034" alt="image" src="https://github.com/chronoxor/NetCoreServer/assets/44324620/71ecde97-6299-4cf2-a4a7-654acc5f69a0">

**Comment by ilsnk** [comment]
@chronoxor I replaced your implementation with kestrel, and started catching this error on my server;
Handled exception looks like:
``` CS 
System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket received a frame with one or more reserved bits set.
   at System.Net.WebSockets.ManagedWebSocket.CloseWithReceiveErrorAndThrowAsync(WebSocketCloseStatus closeStatus, WebSocketError error, String errorMessage, Exception innerException)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
```

The frequency of this error coincides with the frequency of crashes of this thread.  I understand that most likely the problem is in my client (which sends a broken frame). I still do not have a clear reproducing, only guesses.

In any case, you need to fix this error - otherwise it may be a planned DDoS servers made with NetCoreServer.

**Comment by baris-btcturk** [comment]
This looks like an issue with parsing 64-bit payloads. For larger payload values current method causes integer overflow and sets the payload to a negative value, which causes a buffer to be read with negative length further down throwing this ArgumentOutOfRangeException.

A quick implementation for parsing payload correctly can be found here: https://github.com/chronoxor/NetCoreServer/pull/329/files
