### ISSUE TITLE
Cannot access a disposed object

### ISSUE THREAD

**Issue by anyway2019** [chronoxor/NetCoreServer#296]
the env:
```
net6.0-windows WPF
```
the version of NetCoreServer:
```
6.7.0
```
the stack trace:
```
Application: PowerFunRowerNet.exe CoreCLR Version: 6.0.2123.36311 .NET Version: 6.0.21 Description:
The process was terminated due to an unhandled exception. 
Exception Info: System.ObjectDisposedException: Cannot access a disposed object. Object name: 'System.Net.Sockets.Socket'. at System.Net.Sockets.Socket.ThrowObjectDisposedException() at System.Net.Sockets.Socket.get_RemoteEndPoint() 
at PowerFunRowerNet.Network.TcpService.PfTcpSession.OnConnected() in E:\pf\powefun-rower-net\Network\TcpService.cs:line 116 at NetCoreServer.TcpSession.Connect(Socket socket) at NetCoreServer.TcpServer.ProcessAccept(SocketAsyncEventArgs e) 
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location --- 
at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
```
the log is :
```
2024-04-22 21:16:34.822 +08:00 [ERR] OnConnected
2024-04-22 21:16:34.822 +08:00 [ERR] OnDisconnected
```

it seems the issue that connect event and disconnect envent trigger at same time still exsits in 6.7.0

**Comment by iBoundary** [comment]
I also encountered this issue. Have you resolved it now? @anyway2019 @chronoxor

**Comment by anyway2019** [comment]
> I also encountered this issue. Have you resolved it now? @anyway2019 @chronoxor

not yet,i just add try catch block.

**Comment by ilsnk** [comment]
We have a similar case

``` CS
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.ThrowObjectDisposedException()
   at System.Net.Sockets.Socket.Send(ReadOnlySpan`1 buffer, SocketFlags socketFlags, SocketError& errorCode)
   at NetCoreServer.TcpSession.Send(ReadOnlySpan`1 buffer) in /src/websocket-server/NetCoreServer/TcpSession.cs:line 283
   at NetCoreServer.WsSession.SendBinary(ReadOnlySpan`1 buffer) in /src/websocket-server/NetCoreServer/WsSession.cs:line 74
```

**Comment by ilsnk** [comment]
@anyway2019 maybe you want contribute this action?)
