### ISSUE TITLE
ArgumentException in Buffer.cs

### ISSUE THREAD

**Issue by moustakakisCon** [chronoxor/NetCoreServer#93]
> Exception Info: System.ArgumentException: Source array was not long enough. Check the source index, length, and the array's lower bounds. (Parameter 'sourceArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int64 sourceIndex, Array destinationArray, Int64 destinationIndex, Int64 length)
   at NetCoreServer.Buffer.Append(Byte[] buffer, Int64 offset, Int64 size)
   at NetCoreServer.HttpRequest.ReceiveHeader(Byte[] buffer, Int32 offset, Int32 size)
   at NetCoreServer.HttpSession.OnReceived(Byte[] buffer, Int64 offset, Int64 size)
   at NetCoreServer.WsSession.OnReceived(Byte[] buffer, Int64 offset, Int64 size)
   at NetCoreServer.TcpSession.ProcessReceive(SocketAsyncEventArgs e)
   at NetCoreServer.TcpSession.TryReceive()
   at NetCoreServer.TcpServer.ProcessAccept(SocketAsyncEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)

unfortunately I could find a way to reproduce the issue..

**Comment by chronoxor** [comment]
It seems that for some your WebSocket handshake did not successfully pass and your session read data as HTTP header for infinite:
```
        protected override void OnReceived(byte[] buffer, long offset, long size)
        {
            // Check for WebSocket handshaked status
            if (WebSocket.WsHandshaked)
            {
                // Prepare receive frame
                WebSocket.PrepareReceiveFrame(buffer, offset, size);
                return;
            }

            base.OnReceived(buffer, offset, size);
        }
```

Please put some breakpoints and try to debug `WebSocket.PerformServerUpgrade()` method in debugger.

**Comment by moustakakisCon** [comment]
Still no luck reproducing it..  I'm keeping wireshark open in hopes that will happen again and be able to capture the packet/data causing it

**Comment by moustakakisCon** [comment]
Not able to reproduce and debug it. closing issue for now
