### ISSUE TITLE
Source array was not long enough. Check the source index, length, and the array's lower bounds. 

### ISSUE THREAD

**Issue by wdwd2233** [chronoxor/NetCoreServer#94]
System.ArgumentException
  HResult=0x80070057
  Message=Source array was not long enough. Check the source index, length, and the array's lower bounds. 
  Source=System.Private.CoreLib
  StackTrace: 
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int64 sourceIndex, Array destinationArray, Int64 destinationIndex, Int64 length)
   at NetCoreServer.Buffer.Append(Byte[] buffer, Int64 offset, Int64 size)
   at NetCoreServer.HttpRequest.ReceiveHeader(Byte[] buffer, Int32 offset, Int32 size)
   at NetCoreServer.HttpSession.OnReceived(Byte[] buffer, Int64 offset, Int64 size)
   at NetCoreServer.TcpSession.ProcessReceive(SocketAsyncEventArgs e)
   at NetCoreServer.TcpSession.TryReceive()
   at NetCoreServer.TcpServer.ProcessAccept(SocketAsyncEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)

**Comment by PeteRoberts** [comment]
I have had this exception stop the server working in a .Net app using 8.0.7.
Do you have any insights into what could cause this?
